# BreezeModified Kitty Colorscheme (Fixed)

# Background & Transparency
background            #31363b
#background_opacity    0.85

# Foreground
foreground            #beb199

# Cursor Colors
cursor               #7092ac 
cursor_text_color    #31363b
bold_is_bright yes


# Normal Colors
color0   #63686d
color1   #c0392b
color2   #01D8DD
color3   #FF5E0E
color4   #01D8DD
color5   #9b59b6
color6   #D17B9A
color7   #01D8DD

# Bright Colors
color8   #CCCCCC
color9   #c0392b
color10  #1cdc9a
color11  #fdbc4b
color12  #01D8DD
color13  #8e44ad
color14  #16a085
color15  #01D8DD

# Faint Colors
color16  #202b32
color17  #783228
color18  #179262
color19  #b65619
color20  #1b668f
color21  #614a73
color22  #186c60
color23  #63686d

# Selection Colors
selection_background  #1b668f
selection_foreground  #eff0f1
