# Load Custom Colorscheme
include breeze_modified.conf

# Set Font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Shape: Choose from 'block', 'beam', or 'underline'
cursor_shape block
#cursor #1b668f
cursor #01D8DD
# Cursor Text: Color of the character under the cursor
# Use 'background' to use the cell's background color
cursor_text_color #E4F0FB
# Thickness (optional): Adjust for beam or underline shapes
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
shell_integration no-cursor


# Fix Transparency (Requires compositor like picom)
background_opacity    0.89
dynamic_background_opacity yes
cursor_trail 1
cursor_trail_decay 0.05 0.15
cursor_trail_start_threshold 7


# Reduce Distraction
cursor_blink_when_typing  no

# Smooth Scrolling
scrolling_smooth yes
confirm_os_window_close 0
# Custom scroll shortcuts
map ctrl+h scroll_line_up
window_padding_width 2 

# Copy / Cut / Paste using AltGr (Right Alt)
map alt+y copy_to_clipboard
map alt+p paste_from_clipboard
