# Load Custom Colorscheme
include breeze_modified.conf

# Set Font
font_family       JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# Fix Transparency (Requires compositor like picom)
background_opacity    0.89
dynamic_background_opacity yes
cursor_trail 7

# Reduce Distraction
cursor_blink_when_typing  no

# Smooth Scrolling
scrolling_smooth yes
confirm_os_window_close 0
# Custom scroll shortcuts
map ctrl+h scroll_line_up
window_padding_width 2 
